version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ../../environments/.game.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
